'use client';

export function getSampleConversation(): string {
  const lines = [
    "User: How do I create a React component with TypeScript?",
    "",
    "Assistant: Here is a simple React component with TypeScript:",
    "",
    "```tsx",
    "interface ButtonProps {",
    "  label: string;",
    "  onClick: () => void;",
    "  variant?: 'primary' | 'secondary';",
    "}",
    "",
    "export function MyButton({ label, onClick, variant = 'primary' }: ButtonProps) {",
    "  return (",
    "    <button",
    "      className={`btn btn-${variant}`}",
    "      onClick={onClick}",
    "    >",
    "      {label}",
    "    </button>",
    "  );",
    "}",
    "```",
    "",
    "And here is the CSS for styling:",
    "",
    "```css",
    ".btn {",
    "  padding: 8px 16px;",
    "  border-radius: 6px;",
    "  font-weight: 500;",
    "  cursor: pointer;",
    "  transition: all 0.2s;",
    "}",
    "",
    ".btn-primary {",
    "  background: #0070f3;",
    "  color: white;",
    "}",
    "",
    ".btn-secondary {",
    "  background: transparent;",
    "  border: 1px solid #333;",
    "  color: #333;",
    "}",
    "```",
    "",
    "This gives you a reusable button with type-safe props and variant support.",
    "",
    "User: Can you add a loading state to it?",
    "",
    "Assistant: Sure! Here is the updated component with a loading state:",
    "",
    "```tsx",
    "interface ButtonProps {",
    "  label: string;",
    "  onClick: () => void;",
    "  variant?: 'primary' | 'secondary';",
    "  isLoading?: boolean;",
    "}",
    "",
    "export function MyButton({",
    "  label,",
    "  onClick,",
    "  variant = 'primary',",
    "  isLoading = false",
    "}: ButtonProps) {",
    "  return (",
    "    <button",
    "      className={`btn btn-${variant}`}",
    "      onClick={onClick}",
    "      disabled={isLoading}",
    "    >",
    '      {isLoading ? "Loading..." : label}',
    "    </button>",
    "  );",
    "}",
    "```",
    "",
    "Now the button accepts an `isLoading` prop that disables interaction and shows loading text.",
  ]
  return lines.join("\n")
}
